language: python

#python:
#  - "2.7"
# # command to install dependencies
# install: "pip install -r requirements.txt"
# # command to run tests
# script: 
# # nothing to do

after_success:
  - "echo SUCCESS"
# test deploy retrieve stackato client
  - "wget http://downloads.activestate.com/stackato/client/v1.7.4/stackato-1.7.4-linux-glibc2.3-x86_64.zip"
  - "unzip *.zip"
  - "./stackato-*/stackato target api.stacka.to"
